### PR TITLE
fmt: pretty {bytes,time}

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Hope this makes sense. Thanks!
## Changes
- prettifies `responseSize` if not already formatted
- prettifies `elapsed` if not already formatted
- swapped the `responseSize` and `elapsed` order (e.g. size is probably less frequently present)

### CODE REVIEW

**Comment by mattdesl** [comment]
Interesting! I'll give it a run with budo to see how it feels. The weird thing about `pretty-ms` is that it sometimes returns seconds instead of ms.

**Comment by yoshuawuyts** [comment]
Yeah, I've found it to be a little weird too. Perhaps just fmt everything to `ms` / `kb`?

**Comment by yoshuawuyts** [comment]
Or should we allow the user to set the format, defaulting to `ms`, `kb` ?

**Comment by yoshuawuyts** [comment]
Closing this PR until #20 is resolved

**Pull request closed without merging**
