### PR TITLE
prettier bytes

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Should make byte reporting less verbose. Copying the implementation from
feross/webtorrent-app#81

Thanks! :sparkles: (and thanks @flet for coming up with this)

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Perhaps hold off until https://github.com/feross/webtorrent-app/issues/50#issuecomment-193629820 is resolved to see if there's something better we can use (':

**Comment by Flet** [comment]
I made a package for it: http://npmjs.com/packages/prettier-bytes

It also cuts the decimal to a single digit per https://github.com/feross/webtorrent-app/issues/50#issuecomment-193629820

```bash
    ✔ bytes: 2335 -> 2.3 kB
    ✔ bytes: 23552 -> 23 kB
    ✔ bytes: 235520 -> 235 kB
    ✔ bytes: 2355520 -> 2.3 MB
    ✔ bytes: 23555520 -> 23 MB
    ✔ bytes: 235555520 -> 235 MB
    ✔ bytes: 2355555520 -> 2.3 GB
    ✔ bytes: 23555555520 -> 23 GB
    ✔ bytes: 235556555520 -> 235 GB
    ✔ bytes: 2355556655520 -> 2.3 TB
    ✔ bytes: 23555566655520 -> 23 TB
    ✔ bytes: 235555566665520 -> 235 TB
```

**Comment by yoshuawuyts** [comment]
Rad, added `prettier-bytes` - @mattdesl what do you think?

**Comment by mattdesl** [comment]
Ya! I think it's good to merge as long as it doesn't mess up columns in budo. 😁 On mobile so can't test or publish right now.

**Comment by yoshuawuyts** [comment]
Tested it locally, and columns are probably even more consistent now ^____^. Merging!

**Comment by yoshuawuyts** [comment]
Published as `v5.0.2` :sparkles:

**Pull request closed without merging**
