### PR TITLE
index: refactor

### LINKED ISSUE #3: use ndjson package
I think we could simplify things by relying on [ndjson](https://www.npmjs.com/package/ndjson) to do the parsing / serialization.

### PR DESCRIPTION
**Pull request by yoshuawuyts**
I was running into a bug with `bole` and had a bit of trouble debugging the `garnish` code; this should hopefully make it just a lil bit better (': Thanks!

## Changes
- turned multiple stream calls into a single stream (less code! :D )
- errors are now correctly propagated because it's a single stream
- piping to stdout is now non-blocking (thank you `stdout-stream`)
- newlines will now render correctly cross-platform (copied the `ndjson` approach)

__edit:__ also closes #3, `ndjson` has a slightly different purpose, the current implementation of `garnish` is close enough / should be faster than piping out from garnish

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Think this could just be a patch release; didn't change any of the tests and they all pass (':

**Comment by yoshuawuyts** [comment]
Also: I didn't use `safe-json-parse` here because `split2` requires lines to be returned. Otherwise I'd go with `safe-json-parse` any day.

**Comment by mattdesl** [comment]
Awesome! :tada: Thanks for the PR.

**Comment by yoshuawuyts** [comment]
:tada: my pleasure! :grin:

**Pull request merged**
