### PR TITLE
strip hash and query parameters from URL

### PR DESCRIPTION
**Pull request by mattdesl**

### CODE REVIEW

**Comment by mattdesl** [comment]
Currently `pathname-match` does not handle full URLs (with protocol etc) so they end up getting stripped to an empty string.

Something like this might be needed:

```
var urlLib = require('url')
function stripUrl (url) {
  if (!url) return ''
  var obj = urlLib.parse(url)
  obj.pathname = (obj.pathname || '').replace(/\/$/, '')
  obj.search = ''
  obj.hash = ''
  obj.query = ''
  return urlLib.format(obj)
}
```

**Comment by yoshuawuyts** [comment]
Good point. Though wouldn't this yield the same result?
```js
const url = require('url')

function strip (route) {
  return url.parse(url).pathname
}
```

**Comment by yoshuawuyts** [comment]
I added an extra test case and it appears `pathname-match` handles full path routes alright. - https://github.com/yoshuawuyts/pathname-match/blob/master/test.js#L19-L21

What path were you testing it with? I'd very much want `pathname-match` to work for all cases.

**Comment by mattdesl** [comment]
In the case of budo I want to be able to log the full URL:

```http://192.168.1.2:9966/```

So that the user knows which IP and port it is serving on. Stripping to pathname would log an empty string.

**Comment by mattdesl** [comment]
I'm going to merge this since it seems like `pathname-match` has a slightly different goal than what I'm after for garnish.

**Comment by yoshuawuyts** [comment]
:tada:

**Pull request merged**
