### PR TITLE
refactor + color styles

### PR DESCRIPTION
**Pull request by mattdesl**
Changes:

- refactored source a bit, splitting things into different files
- updates to readme
- removed the regex replace [here](https://github.com/mattdesl/garnish/blob/3ba8f85171730b86da21799f14f37db8ba7b01b7/index.js#L66) since it isn't clear why it was needed (originally from @hughsk's bistre)
- added support for `colors` field

Currently I'm eyeballing it with `npm run demo` but it would be good to actually check the ANSI codes to make sure they line up.

/cc @yoshuawuyts

### CODE REVIEW

**Comment by mattdesl** [comment]
Result with budo. :tada: 

screen shot 2015-09-10 at 12 45 09 pm

**Comment by yoshuawuyts** [comment]
Tests appear to be failing.
```txt
~/src/mattdesl/garnish mattdesl-feature/color
❯ npm t

> garnish@3.1.0 test /Users/yw/src/mattdesl/garnish
> standard && node test/test.js

standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/yw/src/mattdesl/garnish/index.js:40:4: Trailing spaces not allowed.
  /Users/yw/src/mattdesl/garnish/lib/renderer.js:36:4: Trailing spaces not allowed.
npm ERR! Test failed.  See above for more details.

~/src/mattdesl/garnish mattdesl-feature/color
❯
```

**Comment by yoshuawuyts** [comment]
Seems to work fine though ^^
screen shot 2015-09-11 at 03 18 32

**Comment by mattdesl** [comment]
Fixed lint bugs

**Comment by yoshuawuyts** [comment]
:sparkles: looks excellent!

**Comment by mattdesl** [comment]
ok pushed to 3.2.0

**Pull request merged**
